
package com.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SayHiServiceService", targetNamespace = "http://demo.hello.webservice.com/", wsdlLocation = "http://localhost:8088/SayHiService?wsdl")
public class SayHiServiceService
    extends Service
{

    private final static URL SAYHISERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYHISERVICESERVICE_EXCEPTION;
    private final static QName SAYHISERVICESERVICE_QNAME = new QName("http://demo.hello.webservice.com/", "SayHiServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/SayHiService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYHISERVICESERVICE_WSDL_LOCATION = url;
        SAYHISERVICESERVICE_EXCEPTION = e;
    }

    public SayHiServiceService() {
        super(__getWsdlLocation(), SAYHISERVICESERVICE_QNAME);
    }

    public SayHiServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAYHISERVICESERVICE_QNAME, features);
    }

    public SayHiServiceService(URL wsdlLocation) {
        super(wsdlLocation, SAYHISERVICESERVICE_QNAME);
    }

    public SayHiServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAYHISERVICESERVICE_QNAME, features);
    }

    public SayHiServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayHiServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SayHiService
     */
    @WebEndpoint(name = "SayHiServicePort")
    public SayHiService getSayHiServicePort() {
        return super.getPort(new QName("http://demo.hello.webservice.com/", "SayHiServicePort"), SayHiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayHiService
     */
    @WebEndpoint(name = "SayHiServicePort")
    public SayHiService getSayHiServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo.hello.webservice.com/", "SayHiServicePort"), SayHiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYHISERVICESERVICE_EXCEPTION!= null) {
            throw SAYHISERVICESERVICE_EXCEPTION;
        }
        return SAYHISERVICESERVICE_WSDL_LOCATION;
    }

}
